apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/host/c/Users/sbigdel/airflow-logs
  storageClassName: manual


#minikube mount C:/Users/sbigdel/airflow-logs:/mnt/airflow-logs