apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-local-logs-folder
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce  
  hostPath:
    path: /mnt/airflow-logs
    type: Directory


#minikube mount C:\Users\sbigdel\airflow-logs:/mnt/airflow-logs