apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv  
spec:
  capacity:
    storage: 10Gi  # Adjust storage size as needed
  accessModes:
    - ReadWriteMany  # Allow multiple pods to read/write
  hostPath:
    path: /mnt/airflow-logs  # Directory inside Docker's Linux VM, adjust as needed


#minikube mount C:/Users/sbigdel/airflow-logs:/mnt/airflow-logs