apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-local-logs-folder
  namespace: airflow
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi    