executor: "KubernetesExecutor"
airflow:
  config:
    logging:
      remote_logging: "True"
      remote_log_conn_id: "aws_default"  # The connection ID from Step 1
      remote_base_log_folder: "s3://airflow-dags-k8s/airflow-logs"
      logging_level: "INFO"  # Set logging level to INFO, but can also set to "ERROR"

dags:  
  gitSync:
    enabled: true
    # Git repository URL
    repo: https://github.com/shadab-bigdel/airflow.git
    branch: main
    # The Git revision to check out (branch, tag, or hash)
    ref: main
    depth: 1
    # Maximum number of consecutive failures allowed before aborting
    maxFailures: 0
    # Subpath within the repo where DAGs are located
    # Should be "" if DAGs are at the repo root
    subPath: "dags"
